### ISSUE TITLE
Scaling i FF 28.0 on Windows 7

### ISSUE THREAD

**Issue by Ruffio** [frequent/JQM-carousel#1]
There seems to be some scaling issues on FF 28.

Your sample fills more than my 1920x1080 screen making the images very large.
Perheps an option to scale down to max screen width?

**Comment by Ruffio** [comment]
After reading the intro, if think there should be an option not to scale larger than width or height. Thereby you will always have the whole picture on the screen

**Comment by frequent** [comment]
@Ruffio 

The widget is setup to fill available space set by its parent. So on an empty page, it will stretch to the full with of `div.ui-content`.

I see what you mean though. Let me think about and play around with the widget a little.

In the meantime, if you want to limit scaling, just wrap in a container like [here](http://jsbin.com/ofuhaw/1288/edit)
