### ISSUE TITLE
Position of image in sequence doesn't affect slide direction

### ISSUE THREAD

**Issue by Ruffio** [frequent/JQM-carousel#2]
When clicking on the buttons below the images causes the carousel to slide in the previous direction, which is wrong. The slide direction should be determined by the position of the images in relation to each other. 
So if picture 2 is shown, clicking on button one should result in a slide left. 
If picture 2 is shown, clicking on button three should result in a slide right.

Tested in FF 28 Windows 7.

**Comment by frequent** [comment]
Yup. Needs to be fixed.

**Comment by frequent** [comment]
@Ruffio 
Should be fixed ([latest JSBIN from documentation](http://jsbin.com/ofuhaw/1290))
